### PR TITLE
jaSelectStoreResources

### PR DESCRIPTION
**Pull request by kawamoto**

### CODE REVIEW

**Comment by tasos31** [comment]
分かってる限り大丈夫そうです。
でも名前は大丈夫なのかな？
Maybe we should use something more descriptive like `jaSelectStoreResourceArray`. I'm not sure what should be considered best practice

**Comment by kawamoto** [comment]
it's plural, I think developers will expect it's array in javascript. and in this library, many function use the word `Resources`

**Comment by tasos31** [comment]
なるほど。If thats the case then it sounds fine

**Comment by kawamoto** [comment]
I'll merge original master branch instead of this feature branch

**Pull request closed without merging**
